// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJOpdY7VUB6ECUTriC-dXDP5sHRi6nD8',
    appId: '1:268663028306:web:3076aedc827bf002a3bd8b',
    messagingSenderId: '268663028306',
    projectId: 'patrol-pal-92902',
    authDomain: 'patrol-pal-92902.firebaseapp.com',
    storageBucket: 'patrol-pal-92902.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ffr66HDH0ixYeLiNfYlu_A3w7K3HJFc',
    appId: '1:268663028306:android:b2b355401fdef04ea3bd8b',
    messagingSenderId: '268663028306',
    projectId: 'patrol-pal-92902',
    storageBucket: 'patrol-pal-92902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5mT0FMxHnunKhjOCfP6NMBAxnExXGAQY',
    appId: '1:268663028306:ios:77ae24fc45b6e984a3bd8b',
    messagingSenderId: '268663028306',
    projectId: 'patrol-pal-92902',
    storageBucket: 'patrol-pal-92902.appspot.com',
    iosClientId: '268663028306-2li64vmudakbpo636jsekp0v96eei0pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.patrolPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5mT0FMxHnunKhjOCfP6NMBAxnExXGAQY',
    appId: '1:268663028306:ios:77ae24fc45b6e984a3bd8b',
    messagingSenderId: '268663028306',
    projectId: 'patrol-pal-92902',
    storageBucket: 'patrol-pal-92902.appspot.com',
    iosClientId: '268663028306-2li64vmudakbpo636jsekp0v96eei0pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.patrolPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZJOpdY7VUB6ECUTriC-dXDP5sHRi6nD8',
    appId: '1:268663028306:web:810644682aa5b781a3bd8b',
    messagingSenderId: '268663028306',
    projectId: 'patrol-pal-92902',
    authDomain: 'patrol-pal-92902.firebaseapp.com',
    storageBucket: 'patrol-pal-92902.appspot.com',
  );

}